---
env:
  es6: true
  node: true
  mocha: true
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

extend: airbnb-base
plugins:
- import