language: node_js
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: true
node_js:
- '7'
before_script:
- yarn lint
- yarn codecov
script:
- yarn build
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
deploy:
  provider: npm
  email: uma.karimov@gmail.com
  api_key:
    secure: BHa9bVPN5aT8KDTdn2OdCZNO7X7zUtuRBvjrJU8tc0wew8CPHUnXs5WCUqYWjbJc+S1MMOl9jWGRdnl6Y67anqxj4T/ePWxUDjYCQOyZ/Qhh/dpavNywhkJVyAItHd5gz161tpHEgMcJ3ACKmJ5p4rtH9Dm9aayb7lWwUmtYyDeZeNjacDN9fe28jMX1asYC3SbGKsjdoEAPDb1lx09fkekmfEwDYfOJmCtCIHPl8Av9KKQZFaqkB24wVEIHLeuVScp+reY82eMMfy69UIEe/3fNGXph2wzvF9i8qe8wgHnCsFlWVCdFDJ/RXq1e7BMrDwWmiC78uWylUphog/K+ZUg6MXZnu4nuv5RgKpFbzMrGnBBdxiF6pXRMlDRsuaM9kRhTLYCXwx+Oq0VxZ1yBb0FXJkRTOSR402Uw4tJIl7Gd+DNN4R9thErwB7SX3Opu+rz16N64MYR6JJWa+7dHoC40Dk4g1iOGDgi+6/l0RGlmdTPVM0+Z4qdNqHcMfLI/Jo1iJiJlc6pcOom59RCaisVYBe9rUuGnFGmbqfJYFiwLnlF0LWLBHrtOVO/D/CqhoAlyv39mWsYlAH/MdbZ9nM84xvthhbd3gcp+yxRjf2SHYnDYj/HAN+nspjyT0hK03zXhSCq9FCClh73OaDkZL65ej9sMfqQioyN4fBhsvSo=
  on:
    tags: true
    repo: umidbekkarimov/babel-plugin-material-ui
