language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '7'
before_install:
  - npm i -g yarn
before_script:
  - yarn
script:
  - npm run cover
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
